services:
  app:
    image: cloud-native-eks-platform-app:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI} # <-- injected from host .env or shell
      - NODE_ENV=development
    # No depends_on anymore â€” Atlas is always available
# No volumes needed anymore
