{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "fintrack.fullname" . }}
  labels:
    {{- include "fintrack.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "fintrack.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: {{ .Values.service.targetPort }}
          protocol: TCP
  egress:
    # Allow DNS resolution
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    # Allow HTTPS (AWS APIs, external calls)
    - ports:
        - port: 443
          protocol: TCP
    # Allow MongoDB Atlas
    - ports:
        - port: 27017
          protocol: TCP
{{- end }}
